services:
    tsk_file_editor.file_manager:
        default:
            public: true
            class: TSK\WebFileEditorBundle\Doctrine\FileManager
            arguments:
                - '@doctrine.orm.entity_manager'
                - '%tsk_file_editor.file_entity.class%'
