tsk_file_editor_list:
    path: /
    controller: tsk_file_editor.file.controller:listAction

tsk_file_editor_add:
    path: /add
    controller: tsk_file_editor.file.controller:addAction

tsk_file_editor_view:
    path: /view/{fileId}
    controller: tsk_file_editor.file.controller:viewAction